app_index:
    path: /index
    defaults: { _controller: AppBundle:Default:index }

app_users:
    path: /users
    defaults: {_controller: AppBundle:Default:users}

app_edit:
    path: /edit/{id}
    defaults: {_controller: AppBundle:Default:edit}

app_delete:
    path: /delete/{id}
    defaults: {_controller: AppBundle:Default:delete}

app_comments:
    path: /comments
    defaults: {_controller: AppBundle:Default:comments}

login:
    path: /login
    defaults: {_controller: AppBundle:Security:login}

login_check:
    path: /login_check

logout:
    path: /logout